module.exports = [
    ["Is the eight ball in pool black or white?", "Black", "White"],
    ["Is Mongolia in Africa or Asia?", "Asia", "Africa"],
    ["Is a hat-trick three goals or five?", "Three", "Five"],
    ["Is a week eight days or seven?", "Seven", "Eight"],
    ["Is a group of crows called a murder or a corpse?", "Murder", "Corpse"],
    ["Was the Roman god of the sea Poseidon or Neptune?", "Neptune", "Poseidon"],
    ["Is the upper arm bone called the femur or the humerus?", "Humerus", "Femur"],
    ["Did Romulus and Remus found Rome or Athens?", "Rome", "Athens"],
    ["Which country is on the Equator, Ecuador or Norway?", "Ecuador", "Norway"],
    ["If you were in Turin, would you be in Greece or Italy?", "Italy", "Greece"],
    ["Which planet has the shortest day, Jupiter or Mercury?", "Jupiter", "Mercury"],
    ["Does Chile share the majority of its border with Argentina or Brazil?", "Argentina", "Brazil"],
    ["Was the oldest member of the Beatles George or Ringo?", "Ringo", "George"],
    ["Was the first man on the moon Armstrong or Aldrin?", "Armstrong", "Aldrin"],
    ["Did Alexander Fleming discover aspirin or penicillin?", "Penicillin", "Aspirin"],
    ["Did Bobby Fischer play chess or poker?", "Chess", "Poker"],
    ["Is a drink on the rocks served with ice or lemon?", "Ice", "Lemon"],
    ["Does champagne traditionally come from America or France?", "France", "America"],
    ["Was the Egg McMuffin introduced in the seventies or the eighties?", "seventies", "eighties"],
    ["Is Torchwood a spinoff of Doctor Who or Star Trek?", "Doctor Who", "Star Trek"],
    ["Was a penny farthing a bicycle or a car?", "Bicycle", "Car"],
    ["Did Charles Darwin travel on the Beagle or the Enterprise?", "Beagle", "Enterprise"],
    ["Was Alaska purchased by the United States from Canada or Russia?", "Russia", "Canada"],
    ["In Friends, was Chandler's last name Geller or Bing?", "Bing", "Geller"]
];
